defaults:
  - cluster: default
  - data: default
  - model: default
  - optim: adamw
  - preprocess: spectrogram
  - trainer
  - _self_

seed: 42

name: ${oc.env:SLURM_JOB_NAME}_${oc.env:SLURM_JOB_ID}

# Weights & Biases configuration
wandb:
  name: ${name}
  project: "train-bfm"
  entity: ""

save_model_every_n_epochs: 1

hydra:
  run:
    dir: outputs/${name}
  job:
    name: ${name}
  job_logging:
    level: INFO
    formatters:
      simple:
        format: "%(asctime)s | %(levelname)s | %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      handlers: [console]
