defaults:
  - cluster: default
  - data: default
  - model: default
  - optim: adamw
  - trainer
  - spectrogram
  - _self_

seed: 42

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
  job:
    name: ${training.setup_name}
  job_logging:
    level: INFO
    formatters:
      simple:
        format: "%(asctime)s | %(levelname)s | %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      handlers: [console]
