# @package _global_
defaults:
  - model: default
  - training: default
  - cluster: default
  - data: default
  - _self_

# Global settings
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
  job:
    name: ${training.setup_name}
  job_logging:
    level: INFO
    formatters:
      simple:
        format: "%(asctime)s | %(levelname)s | %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      handlers: [console]


# Override any settings here if needed
# For example:
# model:
#   transformer:
#     d_model: 256
